spring.application.name=api-using-jwt

spring.datasource.url=jdbc:postgresql://localhost:5432/jwtSecurity
spring.datasource.username=postgres
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver

spring.sql.init.mode=always
spring.jpa.show-sql=false
spring.jpa.hibernate.ddl-auto=update

app.jwt.secret=abcdefghijklmnopqrstuvwxyz0123456789
app.jwt.access.minutes=15
app.jwt.refresh.days=7
